name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        react-version: ["^16.8.0", "^17", "^18", "^19"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm --workspace packages/react-hotkeys-hook install --frozen-lockfile && npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Build Documentation
        run: npm run build:documentation
        env:
          CI: true
